-- Create the keepalive_log table
create table if not exists public.keepalive_log (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optional: Enable Row Level Security (RLS) if you want to restrict access
alter table public.keepalive_log enable row level security;

-- Optional: Create a policy if you need access via API (not needed for direct connection usually, but good practice)
-- create policy "Allow public read-only access"
--   on public.keepalive_log for select
--   using ( true );
